### **Exercise: Sentiment Analysis and Key Insights Extraction from Ford Car Reviews**

### **Problem Statement:**
You have been provided with a dataset containing Ford car reviews. Your task is to use LangChain and the concepts you’ve learned to perform the following tasks:

1. **Sentiment Analysis**: Analyze the sentiment of each review, categorize it as positive, neutral, or negative, and store the result.
2. **Key Insights Extraction**: Extract key pieces of information from each review, such as the pros and cons mentioned, and the specific features the reviewer liked or disliked (e.g., vehicle performance, comfort, price).

You will build a LangChain-based solution that leverages language models to automatically extract this information and provide a structured summary of the reviews. 

---
### **Steps to Solve:**

#### **Step 1: Load the Dataset**
- The dataset file is named `ford_car_reviews.csv` and is sourced from Kaggle: [Edmunds Consumer Car Ratings and Reviews](https://www.kaggle.com/datasets/ankkur13/edmundsconsumer-car-ratings-and-reviews).
- For this exercise, **limit the data to the first 25 records**. This can be achieved by using `df.head(25)` or `df.iloc[:25]` when loading the data into a DataFrame.

#### **Step 2: Define the Sentiment Analysis Task**
- Use LangChain to create a pipeline to classify the sentiment of each review.
- Define prompts that can guide the model to evaluate the sentiment. For example:
  - "Given the following car review, classify the sentiment as positive, neutral, or negative."

#### **Step 3: Key Insights Extraction**
- Use LangChain to create a pipeline to extract pros, cons, and notable features from each review. Define prompts such as:
  - "What are the pros and cons of the vehicle described in the following review?"
  - "What specific features of the vehicle does the reviewer like or dislike?"

#### **Step 4: Update the DataFrame with New Information**
- Run the pipeline for each review and collect the sentiment and insights.
- Once the analysis and extraction are complete, update the original DataFrame with additional columns to include:
  - Sentiment (positive, neutral, negative)
  - Pros
  - Cons
  - Liked_Features
  - Disliked_Features

---

### **Example Output:**

```json
{
  "Review_Date": "03/07/13",
  "Vehicle_Title": "2006 Ford Mustang Coupe",
  "Review_Text": "With the expected arrival of our 6th child...",
  "Rating": 4.125,
  "Sentiment": "Positive",
  "Pros": "Good driving experience, Large seating capacity, Great options",
  "Cons": "None mentioned",
  "Liked_Features": ["Driving experience", "Seating capacity", "Options available"],
  "Disliked_Features": []
}
```

In [4]:
import kagglehub

path = kagglehub.dataset_download(
    "ankkur13/edmundsconsumer-car-ratings-and-reviews"
)

print(path)

Downloading to C:\Users\Admin\.cache\kagglehub\datasets\ankkur13\edmundsconsumer-car-ratings-and-reviews\3.archive...

100%|██████████| 50.3M/50.3M [00:05<00:00, 9.71MB/s]

Extracting files...

C:\Users\Admin\.cache\kagglehub\datasets\ankkur13\edmundsconsumer-car-ratings-and-reviews\versions\3

In [6]:
import os

print(os.listdir(path))

['Scraped_Car_Review_dodge.csv', 'Scraped_Car_Review_ferrari.csv', 'Scraped_Car_Review_fiat.csv', 'Scraped_Car_Review_ford.csv', 'Scraped_Car_Review_genesis.csv', 'Scraped_Car_Review_hummer.csv', 'Scraped_Car_Review_hyundai.csv', 'Scraped_Car_Review_infiniti.csv', 'Scraped_Car_Review_isuzu.csv', 'Scraped_Car_Review_jaguar.csv', 'Scraped_Car_Review_jeep.csv', 'Scraped_Car_Review_kia.csv', 'Scraped_Car_Review_lamborghini.csv', 'Scraped_Car_Review_land-rover.csv', 'Scraped_Car_Review_lexus.csv', 'Scraped_Car_Review_lincoln.csv', 'Scraped_Car_Review_lotus.csv', 'Scraped_Car_Review_maserati.csv', 'Scraped_Car_Review_maybach.csv', 'Scraped_Car_Review_mazda.csv', 'Scraped_Car_Review_mclaren.csv', 'Scraped_Car_Review_mercedes-benz.csv', 'Scraped_Car_Review_mercury.csv', 'Scraped_Car_Review_mini.csv', 'Scraped_Car_Review_mitsubishi.csv', 'Scraped_Car_Review_nissan.csv', 'Scraped_Car_Review_pontiac.csv', 'Scraped_Car_Review_porsche.csv', 'Scraped_Car_Review_ram.csv', 'Scraped_Car_Review_rolls-royce.csv', 'Scraped_Car_Review_subaru.csv', 'Scraped_Car_Review_suzuki.csv', 'Scraped_Car_Review_tesla.csv', 'Scraped_Car_Review_volvo.csv', 'Scrapped_Car_Reviews_Acura.csv', 'Scrapped_Car_Reviews_AlfaRomeo.csv', 'Scrapped_Car_Reviews_AMGeneral.csv', 'Scrapped_Car_Reviews_AstonMartin.csv', 'Scrapped_Car_Reviews_Audi.csv', 'Scrapped_Car_Reviews_Bentley.csv', 'Scrapped_Car_Reviews_BMW.csv', 'Scrapped_Car_Reviews_GMC.csv', 'Scrapped_Car_Reviews_Honda.csv', 'Scrapped_Car_Reviews_Toyota.csv', 'Scrapped_Car_Reviews_Volkswagen.csv', 'Scrapped_Car_Review_Bugatti.csv', 'Scrapped_Car_Review_Buick.csv', 'Scrapped_Car_Review_Cadillac.csv', 'Scrapped_Car_Review_Chevrolet.csv', 'Scrapped_Car_Review_chrysler.csv']

In [9]:
import pandas as pd

file_path = os.path.join(path, "Scraped_Car_Review_ford.csv")

In [11]:
df = pd.read_csv(file_path,engine="python")

In [12]:
df.head(25)

,Unnamed: 0,Review_Date,Author_Name,Vehicle_Title,Review_Title,Review,Rating
0,0,on 06/06/18 14:19 PM (PDT),Vicki,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Mustang GT,Doesn’t disappoint,5.000
1,1,on 08/12/17 06:06 AM (PDT),Tom,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,DREAM CAR,I bought mine 4/17 with 98K. Have been wantin...,3.000
2,2,on 06/15/17 05:43 AM (PDT),Ray,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Ride,There will always be a 05-09 mustang for sale...,5.000
3,3,on 05/18/17 17:33 PM (PDT),Don Watson,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,I have wanted a Mustang for 40 years.,I bought my car from an auction I work at ( A...,5.000
4,4,on 01/03/16 18:03 PM (PST),One owner,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,One owner,I bought this car spankin new and i still am ...,5.000
5,5,on 10/24/15 12:40 PM (PDT),Adam,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Poor,"Lots of problems with Ford these days, sensor...",3.000
6,6,on 10/29/11 04:57 AM (PDT),amos247,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,06 mustang gt with a few mods,Bought mine used 20k on it and have added a S...,4.625
7,7,on 07/25/11 12:15 PM (PDT),dave3012,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Ford Mustang GT Premium 2dr Coupe (4.6L 8...,I bought my preowned 06 a few weeks back and ...,4.375
8,8,on 07/21/11 11:28 AM (PDT),ronnzy98,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Get Rid of it before 100K,I drive 50 miles each way to work and traded ...,3.500
9,9,on 12/06/10 00:00 AM (PST),Anonymous,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Get this car.,This car is just awesome. The 4.6L V8 makes ...,4.625
10,10,on 10/29/10 00:00 AM (PDT),Stu,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Fun stang,Only had car for one week and this car put th...,4.500
11,11,on 08/22/10 17:37 PM (PDT),shackm,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Well worth the wait!,Previous mustang owner (1980) and have had a ...,4.750
12,12,on 08/20/10 10:34 AM (PDT),Chet,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,166K miles and still going strong,"I drive a lot of miles, at least 150/day. I ...",4.875
13,13,on 07/22/10 15:00 PM (PDT),Max Lives,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Max Lives,"I purchased this Horsey in memory of my dad, ...",4.625
14,14,on 06/19/10 10:05 AM (PDT),kells,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,"Great car, couple of issues","Dash board rattles, dealer couldn't fix it, f...",4.375
15,15,on 06/11/10 17:13 PM (PDT),DLJ,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Only a few minior issues,I drive very little (about 5k miles per year)...,4.375
16,16,on 04/28/10 06:15 AM (PDT),Carl,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,It is what it is,This was my first new car purchase and I real...,3.750
17,17,on 04/19/10 01:31 AM (PDT),shibemw,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Lemon Mustang,Nice styling car and fun to drive when it is ...,4.000
18,18,on 03/01/10 18:21 PM (PST),DuaneW,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,So so....,I was exceptionally impressed with the down a...,4.750
19,19,on 02/24/10 20:54 PM (PST),Ted,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great looking car,I purchased the Mustang new with every option...,4.000
20,20,on 01/18/10 08:51 AM (PST),ilcoolj,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,"Worst Mustang ever, Don't buy Ford !!!","09/23/06 I financed a '06 Mustang GT, my 1st ...",3.375
21,21,on 11/28/09 19:36 PM (PST),StangGirl731,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,My 1st Stang !,This car is a blast. I purchased my 06' Perfo...,4.875
22,22,on 11/12/09 08:34 AM (PST),stevie,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,great car bad battery and window system,I love to drive the car and to look at the ca...,4.500
23,23,on 09/23/09 09:09 AM (PDT),ChristaK,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Car,It's noisy. It rides rough. It's uncomfortab...,4.625
24,24,on 08/16/09 21:41 PM (PDT),MustangKenny,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Dreams are well worth working for!,I've always wanted a V8 Mustang since my dad ...,4.625

In [63]:
df_final = (
    df[df["Review_Date"].notna()]
    .groupby("Rating")
    .head(10)
    .reset_index(drop=True)
)

# Data Cleaning

In [64]:
print(df_final.shape)

(330, 6)

In [65]:
print(df_final.columns)

Index(['Review_Date', 'Author_Name', 'Vehicle_Title', 'Review_Title', 'Review',
       'Rating'],
      dtype='object')

In [66]:
df_final.isnull().sum()

Review_Date      0
Author_Name      0
Vehicle_Title    0
Review_Title     0
Review           0
Rating           0
dtype: int64

In [84]:
df_final.duplicated().sum()

np.int64(0)

In [86]:
df_final

,review_date,author_name,vehicle_title,review_title,review,rating
0,NaN,Vicki,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Mustang GT,Doesn’t disappoint,5.000
1,2017-08-12,Tom,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,DREAM CAR,I bought mine 4/17 with 98K. Have been wanting...,3.000
2,2017-06-15,Ray,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Ride,There will always be a 05-09 mustang for sale ...,5.000
3,NaN,Don Watson,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,I have wanted a Mustang for 40 years.,I bought my car from an auction I work at ( Ad...,5.000
4,NaN,One owner,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,One owner,I bought this car spankin new and i still am I...,5.000
5,2015-10-24,Adam,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Poor,"Lots of problems with Ford these days, sensors...",3.000
6,2011-10-29,amos247,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,06 mustang gt with a few mods,Bought mine used 20k on it and have added a SC...,4.625
7,2011-07-25,dave3012,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Ford Mustang GT Premium 2dr Coupe (4.6L 8...,I bought my preowned 06 a few weeks back and a...,4.375
8,2011-07-21,ronnzy98,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Get Rid of it before 100K,I drive 50 miles each way to work and traded m...,3.500
9,2010-12-06,Anonymous,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Get this car.,This car is just awesome. The 4.6L V8 makes t...,4.625
10,2010-10-29,Stu,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Fun stang,Only had car for one week and this car put the...,4.500
11,NaN,shackm,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Well worth the wait!,Previous mustang owner (1980) and have had a s...,4.750
12,2010-08-20,Chet,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,166K miles and still going strong,"I drive a lot of miles, at least 150/day. I j...",4.875
13,NaN,Max Lives,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Max Lives,"I purchased this Horsey in memory of my dad, M...",4.625
14,2010-06-19,kells,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,"Great car, couple of issues","Dash board rattles, dealer couldn't fix it, fi...",4.375
15,NaN,DLJ,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Only a few minior issues,"I drive very little (about 5k miles per year),...",4.375
16,2010-04-28,Carl,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,It is what it is,This was my first new car purchase and I reall...,3.750
17,2010-04-19,shibemw,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Lemon Mustang,Nice styling car and fun to drive when it is n...,4.000
18,NaN,DuaneW,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,So so....,I was exceptionally impressed with the down an...,4.750
19,NaN,Ted,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great looking car,I purchased the Mustang new with every option ...,4.000
20,2010-01-18,ilcoolj,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,"Worst Mustang ever, Don't buy Ford !!!","09/23/06 I financed a '06 Mustang GT, my 1st n...",3.375
21,NaN,StangGirl731,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,My 1st Stang !,This car is a blast. I purchased my 06' Perfor...,4.875
22,2009-11-12,stevie,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,great car bad battery and window system,I love to drive the car and to look at the car...,4.500
23,2009-09-23,ChristaK,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Car,It's noisy. It rides rough. It's uncomfortabl...,4.625
24,NaN,MustangKenny,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Dreams are well worth working for!,I've always wanted a V8 Mustang since my dad s...,4.625

In [97]:
df_final.columns = (
    df_final.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [98]:
df_final

,review_date,author_name,vehicle_title,review_title,review,rating
0,NaN,Vicki,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Mustang GT,Doesn’t disappoint,5.000
1,2017-08-12,Tom,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,DREAM CAR,I bought mine 4/17 with 98K. Have been wanting...,3.000
2,2017-06-15,Ray,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Ride,There will always be a 05-09 mustang for sale ...,5.000
3,NaN,Don Watson,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,I have wanted a Mustang for 40 years.,I bought my car from an auction I work at ( Ad...,5.000
4,NaN,One owner,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,One owner,I bought this car spankin new and i still am I...,5.000
5,2015-10-24,Adam,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Poor,"Lots of problems with Ford these days, sensors...",3.000
6,2011-10-29,amos247,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,06 mustang gt with a few mods,Bought mine used 20k on it and have added a SC...,4.625
7,2011-07-25,dave3012,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Ford Mustang GT Premium 2dr Coupe (4.6L 8...,I bought my preowned 06 a few weeks back and a...,4.375
8,2011-07-21,ronnzy98,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Get Rid of it before 100K,I drive 50 miles each way to work and traded m...,3.500
9,2010-12-06,Anonymous,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Get this car.,This car is just awesome. The 4.6L V8 makes t...,4.625
10,2010-10-29,Stu,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Fun stang,Only had car for one week and this car put the...,4.500
11,NaN,shackm,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Well worth the wait!,Previous mustang owner (1980) and have had a s...,4.750
12,2010-08-20,Chet,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,166K miles and still going strong,"I drive a lot of miles, at least 150/day. I j...",4.875
13,NaN,Max Lives,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Max Lives,"I purchased this Horsey in memory of my dad, M...",4.625
14,2010-06-19,kells,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,"Great car, couple of issues","Dash board rattles, dealer couldn't fix it, fi...",4.375
15,NaN,DLJ,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Only a few minior issues,"I drive very little (about 5k miles per year),...",4.375
16,2010-04-28,Carl,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,It is what it is,This was my first new car purchase and I reall...,3.750
17,2010-04-19,shibemw,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Lemon Mustang,Nice styling car and fun to drive when it is n...,4.000
18,NaN,DuaneW,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,So so....,I was exceptionally impressed with the down an...,4.750
19,NaN,Ted,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great looking car,I purchased the Mustang new with every option ...,4.000
20,2010-01-18,ilcoolj,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,"Worst Mustang ever, Don't buy Ford !!!","09/23/06 I financed a '06 Mustang GT, my 1st n...",3.375
21,NaN,StangGirl731,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,My 1st Stang !,This car is a blast. I purchased my 06' Perfor...,4.875
22,2009-11-12,stevie,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,great car bad battery and window system,I love to drive the car and to look at the car...,4.500
23,2009-09-23,ChristaK,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Car,It's noisy. It rides rough. It's uncomfortabl...,4.625
24,NaN,MustangKenny,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Dreams are well worth working for!,I've always wanted a V8 Mustang since my dad s...,4.625

In [99]:
text_columns = [
    "author_name",
    "vehicle_title",
    "review_title",
    "review"
]

for col in text_columns:
    df_final[col] = df_final[col].str.strip()

In [100]:
df_final["rating"] = pd.to_numeric(df_final["rating"], errors="coerce")

In [101]:
df_final

,review_date,author_name,vehicle_title,review_title,review,rating
0,NaN,Vicki,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Mustang GT,Doesn’t disappoint,5.000
1,2017-08-12,Tom,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,DREAM CAR,I bought mine 4/17 with 98K. Have been wanting...,3.000
2,2017-06-15,Ray,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Ride,There will always be a 05-09 mustang for sale ...,5.000
3,NaN,Don Watson,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,I have wanted a Mustang for 40 years.,I bought my car from an auction I work at ( Ad...,5.000
4,NaN,One owner,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,One owner,I bought this car spankin new and i still am I...,5.000
5,2015-10-24,Adam,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Poor,"Lots of problems with Ford these days, sensors...",3.000
6,2011-10-29,amos247,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,06 mustang gt with a few mods,Bought mine used 20k on it and have added a SC...,4.625
7,2011-07-25,dave3012,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Ford Mustang GT Premium 2dr Coupe (4.6L 8...,I bought my preowned 06 a few weeks back and a...,4.375
8,2011-07-21,ronnzy98,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Get Rid of it before 100K,I drive 50 miles each way to work and traded m...,3.500
9,2010-12-06,Anonymous,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Get this car.,This car is just awesome. The 4.6L V8 makes t...,4.625
10,2010-10-29,Stu,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Fun stang,Only had car for one week and this car put the...,4.500
11,NaN,shackm,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Well worth the wait!,Previous mustang owner (1980) and have had a s...,4.750
12,2010-08-20,Chet,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,166K miles and still going strong,"I drive a lot of miles, at least 150/day. I j...",4.875
13,NaN,Max Lives,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Max Lives,"I purchased this Horsey in memory of my dad, M...",4.625
14,2010-06-19,kells,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,"Great car, couple of issues","Dash board rattles, dealer couldn't fix it, fi...",4.375
15,NaN,DLJ,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Only a few minior issues,"I drive very little (about 5k miles per year),...",4.375
16,2010-04-28,Carl,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,It is what it is,This was my first new car purchase and I reall...,3.750
17,2010-04-19,shibemw,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Lemon Mustang,Nice styling car and fun to drive when it is n...,4.000
18,NaN,DuaneW,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,So so....,I was exceptionally impressed with the down an...,4.750
19,NaN,Ted,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great looking car,I purchased the Mustang new with every option ...,4.000
20,2010-01-18,ilcoolj,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,"Worst Mustang ever, Don't buy Ford !!!","09/23/06 I financed a '06 Mustang GT, my 1st n...",3.375
21,NaN,StangGirl731,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,My 1st Stang !,This car is a blast. I purchased my 06' Perfor...,4.875
22,2009-11-12,stevie,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,great car bad battery and window system,I love to drive the car and to look at the car...,4.500
23,2009-09-23,ChristaK,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Car,It's noisy. It rides rough. It's uncomfortabl...,4.625
24,NaN,MustangKenny,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Dreams are well worth working for!,I've always wanted a V8 Mustang since my dad s...,4.625

In [102]:
df_final["review_date"] = (
    df_final["review_date"]
    .str.replace("on ", "", regex=False)
    .str.replace(r" \([A-Z]+\)$", "", regex=True)
)

In [103]:
df_final

,review_date,author_name,vehicle_title,review_title,review,rating
0,NaN,Vicki,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Mustang GT,Doesn’t disappoint,5.000
1,2017-08-12,Tom,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,DREAM CAR,I bought mine 4/17 with 98K. Have been wanting...,3.000
2,2017-06-15,Ray,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Ride,There will always be a 05-09 mustang for sale ...,5.000
3,NaN,Don Watson,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,I have wanted a Mustang for 40 years.,I bought my car from an auction I work at ( Ad...,5.000
4,NaN,One owner,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,One owner,I bought this car spankin new and i still am I...,5.000
5,2015-10-24,Adam,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Poor,"Lots of problems with Ford these days, sensors...",3.000
6,2011-10-29,amos247,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,06 mustang gt with a few mods,Bought mine used 20k on it and have added a SC...,4.625
7,2011-07-25,dave3012,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Ford Mustang GT Premium 2dr Coupe (4.6L 8...,I bought my preowned 06 a few weeks back and a...,4.375
8,2011-07-21,ronnzy98,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Get Rid of it before 100K,I drive 50 miles each way to work and traded m...,3.500
9,2010-12-06,Anonymous,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Get this car.,This car is just awesome. The 4.6L V8 makes t...,4.625
10,2010-10-29,Stu,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Fun stang,Only had car for one week and this car put the...,4.500
11,NaN,shackm,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Well worth the wait!,Previous mustang owner (1980) and have had a s...,4.750
12,2010-08-20,Chet,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,166K miles and still going strong,"I drive a lot of miles, at least 150/day. I j...",4.875
13,NaN,Max Lives,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Max Lives,"I purchased this Horsey in memory of my dad, M...",4.625
14,2010-06-19,kells,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,"Great car, couple of issues","Dash board rattles, dealer couldn't fix it, fi...",4.375
15,NaN,DLJ,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Only a few minior issues,"I drive very little (about 5k miles per year),...",4.375
16,2010-04-28,Carl,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,It is what it is,This was my first new car purchase and I reall...,3.750
17,2010-04-19,shibemw,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Lemon Mustang,Nice styling car and fun to drive when it is n...,4.000
18,NaN,DuaneW,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,So so....,I was exceptionally impressed with the down an...,4.750
19,NaN,Ted,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great looking car,I purchased the Mustang new with every option ...,4.000
20,2010-01-18,ilcoolj,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,"Worst Mustang ever, Don't buy Ford !!!","09/23/06 I financed a '06 Mustang GT, my 1st n...",3.375
21,NaN,StangGirl731,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,My 1st Stang !,This car is a blast. I purchased my 06' Perfor...,4.875
22,2009-11-12,stevie,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,great car bad battery and window system,I love to drive the car and to look at the car...,4.500
23,2009-09-23,ChristaK,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Car,It's noisy. It rides rough. It's uncomfortabl...,4.625
24,NaN,MustangKenny,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Dreams are well worth working for!,I've always wanted a V8 Mustang since my dad s...,4.625

In [104]:
df_final["review_date"] = pd.to_datetime(df_final["review_date"], errors="coerce").dt.strftime("%Y-%m-%d")

In [105]:
df_final.tail(50)

,review_date,author_name,vehicle_title,review_title,review,rating
0,NaN,Vicki,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Mustang GT,Doesn’t disappoint,5.000
1,2017-08-12,Tom,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,DREAM CAR,I bought mine 4/17 with 98K. Have been wanting...,3.000
2,2017-06-15,Ray,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Ride,There will always be a 05-09 mustang for sale ...,5.000
3,NaN,Don Watson,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,I have wanted a Mustang for 40 years.,I bought my car from an auction I work at ( Ad...,5.000
4,NaN,One owner,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,One owner,I bought this car spankin new and i still am I...,5.000
5,2015-10-24,Adam,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Poor,"Lots of problems with Ford these days, sensors...",3.000
6,2011-10-29,amos247,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,06 mustang gt with a few mods,Bought mine used 20k on it and have added a SC...,4.625
7,2011-07-25,dave3012,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,2006 Ford Mustang GT Premium 2dr Coupe (4.6L 8...,I bought my preowned 06 a few weeks back and a...,4.375
8,2011-07-21,ronnzy98,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Get Rid of it before 100K,I drive 50 miles each way to work and traded m...,3.500
9,2010-12-06,Anonymous,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Get this car.,This car is just awesome. The 4.6L V8 makes t...,4.625
10,2010-10-29,Stu,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Fun stang,Only had car for one week and this car put the...,4.500
11,NaN,shackm,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,Well worth the wait!,Previous mustang owner (1980) and have had a s...,4.750
12,2010-08-20,Chet,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,166K miles and still going strong,"I drive a lot of miles, at least 150/day. I j...",4.875
13,NaN,Max Lives,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Max Lives,"I purchased this Horsey in memory of my dad, M...",4.625
14,2010-06-19,kells,2006 Ford Mustang Coupe V6 Deluxe 2dr Coupe (4...,"Great car, couple of issues","Dash board rattles, dealer couldn't fix it, fi...",4.375
15,NaN,DLJ,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,Only a few minior issues,"I drive very little (about 5k miles per year),...",4.375
16,2010-04-28,Carl,2006 Ford Mustang Coupe V6 Standard 2dr Coupe ...,It is what it is,This was my first new car purchase and I reall...,3.750
17,2010-04-19,shibemw,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Lemon Mustang,Nice styling car and fun to drive when it is n...,4.000
18,NaN,DuaneW,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,So so....,I was exceptionally impressed with the down an...,4.750
19,NaN,Ted,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great looking car,I purchased the Mustang new with every option ...,4.000
20,2010-01-18,ilcoolj,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,"Worst Mustang ever, Don't buy Ford !!!","09/23/06 I financed a '06 Mustang GT, my 1st n...",3.375
21,NaN,StangGirl731,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,My 1st Stang !,This car is a blast. I purchased my 06' Perfor...,4.875
22,2009-11-12,stevie,2006 Ford Mustang Coupe GT Premium 2dr Coupe (...,great car bad battery and window system,I love to drive the car and to look at the car...,4.500
23,2009-09-23,ChristaK,2006 Ford Mustang Coupe V6 Premium 2dr Coupe (...,Great Car,It's noisy. It rides rough. It's uncomfortabl...,4.625
24,NaN,MustangKenny,2006 Ford Mustang Coupe GT Deluxe 2dr Coupe (4...,Dreams are well worth working for!,I've always wanted a V8 Mustang since my dad s...,4.625

In [106]:
df_final.describe()

          rating
count  25.000000
mean    4.365000
std     0.609089
min     3.000000
25%     4.000000
50%     4.625000
75%     4.750000
max     5.000000

In [107]:
import os, json, re, getpass
from dotenv import load_dotenv

load_dotenv( override=True)

True

In [108]:
if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass.getpass("GROQ API Key: ")

In [109]:
if os.environ["GROQ_API_KEY"]:
    print(f"Groq API Key exists and begins {os.environ["GROQ_API_KEY"][:4]}")
else:
    print("Groq API Key not set (and this is optional)")

Groq API Key exists and begins gsk_

In [83]:
#Using LangChain
from langchain.chat_models import init_chat_model

model_name = "openai/gpt-oss-120b"
llm = init_chat_model(model_name, model_provider="groq")

In [127]:
from langchain_core.prompts import ChatPromptTemplate

SYSTEM_PROMPT="You are an Sentiment Analyzer Assistant, your task is to classify the given reviews, also extract the structured output according to the attached schema"
PROMPT="Analyze the sentiment of each review, categorize it as positive, neutral, or negative, and store the result. Extract key pieces of information from each review, such as the pros and cons mentioned, and the specific features the reviewer liked or disliked (e.g., vehicle performance, comfort, price)."

In [116]:
from pydantic import BaseModel, Field

class ReviewSchema(BaseModel):
  Review_Date: str =Field(description="The date of review"),
  Vehicle_Title: str =Field(description="The full name/model of the car"),
  Review_Text: str =Field(description="The compelete review provided by the user"),
  Sentiment : str =Field(description="The overall sentiment : Positive, Negative or Neutral"),
  Pros: str =Field(description="All pros separated by commas, and each of them in quotes, return None if not present "),
  Cons: str =Field(description="All cons separated by commas, and each of them in quotes, return None if not present "),
  Liked_Features: list =Field(description="All features liked by the reviewer, empty if not present "),
  Disliked_Features: list =Field(description="All features liked by the reviewer, empty if not present ")

In [117]:
import os, json, re, getpass
from dotenv import load_dotenv

load_dotenv( override=True)

True

In [118]:
if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass.getpass("GROQ API Key: ")

In [119]:
from langchain.chat_models import init_chat_model
model_name = "openai/gpt-oss-120b" ##set GPT OSS 120B as the LLM for this lab

In [120]:
#Initialize LLM without native support
llm = init_chat_model(model_name, 
                      model_provider="groq")

In [121]:
llm.invoke('Hi,who are you')

AIMessage(content='Hello! I’m ChatGPT, an AI language model created by OpenAI. I’m here to help answer questions, discuss topics, brainstorm ideas, or just chat about whatever’s on your mind. How can I assist you today?', additional_kwargs={'reasoning_content': 'The user asks "Hi,who are you". We should respond with friendly greeting, introduce ourselves as ChatGPT, large language model, mention we can assist, follow policy. No disallowed content. Provide brief intro.'}, response_metadata={'token_usage': {'completion_tokens': 101, 'prompt_tokens': 76, 'total_tokens': 177, 'completion_time': 0.212189117, 'prompt_time': 0.03295215, 'queue_time': 0.321286949, 'total_time': 0.245141267, 'completion_tokens_details': {'reasoning_tokens': 45}}, 'model_name': 'openai/gpt-oss-120b', 'system_fingerprint': 'fp_87b3c396db', 'service_tier': 'on_demand', 'finish_reason': 'stop', 'logprobs': None}, id='run--aea38eba-f3ea-49dc-8723-fb53fb636685-0', usage_metadata={'input_tokens': 76, 'output_tokens': 101, 'total_tokens': 177})

In [122]:
from langchain_core.output_parsers import JsonOutputParser
parser = JsonOutputParser(pydantic_object=ReviewSchema)

In [123]:
chain = llm | parser

In [124]:
test=df.iloc[0]

In [128]:
#Get response
llm_response = chain.invoke(PROMPT+str(test))
print(llm_response)

{'review_id': 0, 'date': '06/06/18 14:19 PM (PDT)', 'author': 'Vicki', 'vehicle': '2006 Ford Mustang Coupe GT Premium 2dr Coupe', 'title': '2006 Mustang GT', 'rating': 5.0, 'sentiment': 'positive', 'pros': ['Overall satisfaction – car doesn’t disappoint', 'Implied strong performance (GT power)', 'Premium trim features'], 'cons': [], 'liked_features': ['Vehicle performance', 'Premium trim / interior features', 'Styling / iconic Mustang look'], 'disliked_features': []}

In [ ]:
results = []

for index, item in df_final.iterrows():
    try:
        llm_response = chain.invoke(PROMPT + str(item))
        results.append(llm_response)

    except Exception as e:
        print(f"Failed at row {index}: {e}")
        results.append(None)

❌ Failed at row 6: Invalid json output: **Sentiment analysis & extraction**

| Field | Value |
|-------|-------|
| **review_id** | 6 |
| **review_date** | 2011‑10‑29 |
| **author_name** | amos247 |
| **vehicle_title** | 2006 Ford Mustang Coupe GT Premium 2dr Coupe |
| **review_title** | 06 mustang gt with a few mods |
| **rating** | 4.625 / 5 |
| **overall_sentiment** | **Positive** (rating > 4, language indicates satisfaction) |
| **pros** | • Purchased used at a “reasonable” $20 k price point  <br>• Added performance modifications (e.g., “SC…” – most likely a super‑charger or similar upgrade)  <br>• Enjoys the increased power/handling that the mods provide |
| **cons** | *None explicitly mentioned in the excerpt.* (No complaints or drawbacks are visible in the provided text.) |
| **features_liked** | • **Performance** – the mods improve acceleration/overall driving fun.<br>• **Price/Value** – buying used for $20 k was considered a good deal. |
| **features_disliked** | *None identified.* |
| **notes / extraction limits** | The review text is truncated after “have added a SC…”.  Consequently, only the opening statements could be analysed.  If the full review contains additional comments (e.g., about comfort, reliability, fuel economy, etc.), those would need to be added to the pros/cons lists. |

**Summary**

The reviewer is clearly pleased with the 2006 Mustang GT.  The high rating (4.625) and the language (“Bought mine used 20k on it and have added a SC…”) point to a **positive** sentiment.  The main advantages highlighted are the **affordable purchase price** and the **performance gains from aftermarket modifications**.  No negative aspects are mentioned in the excerpt, so the cons list is empty.  If a more complete version of the review becomes available, additional pros/cons (e.g., comfort, fuel economy, reliability) can be appended.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE
❌ Failed at row 9: Invalid json output: **Sentiment & Information Extraction**

| Field                | Extracted Value |
|----------------------|-----------------|
| **review_date**      | 2010‑12‑06 |
| **author_name**      | Anonymous |
| **vehicle_title**    | 2006 Ford Mustang Coupe GT Premium 2dr Coupe |
| **review_title**     | Get this car. |
| **rating**           | 4.625 (out of 5) |
| **sentiment**        | **Positive** |
| **pros**             | • “just awesome” – overall enthusiasm  <br>• “The 4.6L V8 makes …” – strong engine performance, power |
| **cons**             | *No explicit cons mentioned in the visible portion of the review.* |
| **features_liked**   | • Engine: 4.6 L V8 (powerful, responsive) <br>• Overall driving excitement / fun factor |
| **features_disliked**| *None identified* |

---

### How to Store the Result (Python Example)

```python
import pandas as pd

# Create a list of dictionaries (one per review)
reviews_parsed = [
    {
        "review_date": "2010-12-06",
        "author_name": "Anonymous",
        "vehicle_title": "2006 Ford Mustang Coupe GT Premium 2dr Coupe",
        "review_title": "Get this car.",
        "rating": 4.625,
        "sentiment": "positive",
        "pros": [
            "Overall awesome experience",
            "Powerful 4.6L V8 engine"
        ],
        "cons": [],                     # empty list → no cons mentioned
        "features_liked": [
            "Engine performance (4.6L V8)",
            "Driving excitement"
        ],
        "features_disliked": []        # empty list → no dislikes identified
    }
]

# Convert to a DataFrame for easy storage / analysis
df_reviews = pd.DataFrame(reviews_parsed)

# Example: save to CSV
df_reviews.to_csv("parsed_reviews.csv", index=False)

# Example: save to a SQLite database
import sqlite3
conn = sqlite3.connect("reviews.db")
df_reviews.to_sql("mustang_reviews", conn, if_exists="replace", index=False)
conn.close()
```

The above code creates a structured record for the review, categorises its sentiment, isolates the pros/cons, and stores the information in a tabular format (CSV or SQLite). You can extend the `reviews_parsed` list with additional reviews and repeat the same process.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE
❌ Failed at row 11: Invalid json output: **Sentiment & Feature Extraction**

| Field                     | Value |
|---------------------------|-------|
| **review_id**             | 11 |
| **author_name**           | shackm |
| **vehicle_title**         | 2006 Ford Mustang Coupe GT Premium 2dr Coupe |
| **review_title**          | Well worth the wait! |
| **rating**                | 4.75 |
| **sentiment** (derived)   | **Positive** (high rating, enthusiastic title) |
| **pros** (mentioned / implied) | • Classic Mustang heritage (previous owner of a 1980 Mustang) <br>• Strong GT performance <br>• Premium‑level equipment and features <br>• Overall driving enjoyment (“well worth the wait”) |
| **cons** (mentioned / implied) | *No explicit cons in the excerpt; none identified.* |
| **specific features liked** | • **Vehicle performance** – GT engine power and handling <br>• **Comfort / interior** – Premium trim level <br>• **Nostalgia / brand heritage** – Connection to earlier Mustang ownership |
| **specific features disliked** | *None noted.* |

> **Note:** The review text was truncated (`“Previous mustang owner (1980) and have had a s…”`). The extraction above is based on the available information (title, rating, and the short snippet). If the full review were available, additional pros, cons, or nuanced sentiment cues could be captured.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE
❌ Failed at row 23: Invalid json output: **Processed Review**

| Field | Value |
|-------|-------|
| **review_id** | 23 |
| **review_date** | 2009‑09‑23 |
| **author_name** | ChristaK |
| **vehicle_title** | 2006 Ford Mustang Coupe V6 Premium 2dr Coupe |
| **review_title** | Great Car |
| **rating** | 4.625 / 5 |
| **sentiment** | **Neutral** (mixed – positive rating but strong negative comments) |
| **pros** | *None explicitly listed* – the reviewer does not mention any positive aspects in the text. |
| **cons** | • Noisy interior/exterior<br>• Rough ride quality<br>• Uncomfortable seating |
| **features mentioned** | • **Noise level** – described as “noisy”.<br>• **Ride quality** – “rides rough”.<br>• **Comfort** – “uncomfortable”. |
| **overall summary** | The reviewer gave the car a high numeric rating (4.625) and titled the review “Great Car”, but the body of the review lists only negative experiences (noise, rough ride, discomfort). Because the textual sentiment is predominantly negative while the star rating is high, the balanced classification is **Neutral** (mixed). |

---

### How the result was derived
1. **Sentiment analysis** – The textual content contains three clear negative statements and no positive statements. The rating (4.625) is high, which would normally indicate a positive sentiment. The conflict leads to a **neutral/mixed** classification.
2. **Pros extraction** – No positive phrases were found, so the “pros” list is empty.
3. **Cons extraction** – Direct negative adjectives/phrases were identified and listed.
4. **Feature extraction** – Each con was mapped to a specific vehicle attribute (noise, ride quality, comfort).

The structured record above can be stored directly in a database or a CSV file for later analysis.
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE